[commands]
    [commands.icon]
    engine = "iconTheme"
    contrib = "iconThemes"
    options = ["main", "list"]
    template = "iconTheme"
    errorMessage = "is not an icon theme plugin"

    [commands.help]
    engine = "help"
    options = ["main", "icon", "help"]
