[commands]
    [commands.make]
    name = "make"
    options = ["main"]
    flags = ["--single"]

    [commands.list]
    name = "list"
    options = ["main"]
    flags = ["-a"]

    [commands.help]
    name = "help"
    options = ["main", "make", "help"]

[contributes]
    [contributes.iconThemes]
    engine = "iconTheme"
    options = ["main", "list"]
    template = "iconTheme"