[[commands]]
name = "build"
flags = ["--single"]

[[commands]]
name = "b"
alias = "build"

[[commands]]
name = "list"
flags = ["-a"]

[[contributes]]
engine = "iconTheme"
options = ["list"]
template = "iconTheme"