[[commands]]
name = "build"
options = ["--single"]

[[commands]]
name = "b"
alias = "build"

[[commands]]
name = "list"
options = ["-a"]

[[engines]]
name = "iconTheme"
contrib = "iconThemes"
template = "iconTheme"