[commands]
    [commands.build]
    name = "build"
    options = ["main"]
    flags = ["--single"]

    [commands.b]
    name = "build"
    options = ["main"]
    flags = ["--single"]

    [commands.list]
    name = "list"
    options = ["main"]
    flags = ["-a"]

    [commands.help]
    name = "help"
    options = ["main", "build", "b", "help"]

[contributes]
    [contributes.iconThemes]
    engine = "iconTheme"
    options = ["main", "list"]
    template = "iconTheme"