[[commands]]
name = "build"
options = ["--single"]
vsix = true

[[commands]]
name = "b"
alias = "build"

[[commands]]
name = "list"
options = ["-a"]
vsix = true

[[engines]]
name = "iconTheme"
contrib = "iconThemes"
template = "iconTheme"
modes = ["--static", "--dynamic"]